services:

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
  piston:
    image: ghcr.io/engineer-man/piston:latest
    container_name: piston_service
    restart: always
    privileged: true
    ports:
      - "2000:2000"
    networks:
      - energyleet-network
    volumes:
      - piston_packages:/piston/packages
    tmpfs:
      - /tmp:exec
    cpuset: "0" # limit to CPU 0
  piston-post-setup:
    image: curlimages/curl:latest
    restart: no
    depends_on:
      piston:
        condition: service_started
    networks:
      - energyleet-network
    volumes:
      - ./init.sh:/init.sh:ro
    entrypoint: ["/bin/sh", "/init.sh"]

networks:
  energyleet-network:
    driver: bridge

volumes:
  piston_packages:
  pgdata: